### ISSUE TITLE
AccordionGroup overrides onToggle of Accordion

### ISSUE THREAD

**Issue by zelitzsi** [Bandwidth/shared-components#170]
AccordionGroup overrides `onToggle` of Accordion.
```jsx
  renderAccordion = accordion => {
    const { expandedKey } = this.state;
    if (!accordion.key) {
      throw new Error('All AccordionGroup accordion children must have a key');
    }
    return React.cloneElement(accordion, {
      isExpanded: expandedKey === accordion.key,
      onToggle: this.createToggleHandler(accordion.key),
    });
  };
```

Instead, it should call the original `onToggle()` in addition to the special toggle handler.

**Comment by a-type** [comment]
We could also perhaps sunset AccordionGroup in favor of Selectable.

**Comment by zelitzsi** [comment]
That could work. I think we can get Accordions to have good spacing automatically using `* + &`.
