### ISSUE TITLE
Determine Long-Term theming solution

### ISSUE THREAD

**Issue by Aubron** [Bandwidth/shared-components#190]
So I understand we tried to go a css variables route for theming, but that it's been held up by browser solutions. We need to figure out our method of theming components so we can identify our default themes and start integrating them into the component library.

My pitch: Integrate `<ThemeProvider>` from `styled-components` into `<BandwidthProvider>`, letting you pass a theme into that and use the exposed theme object it wherever possible in components.

Interested in history, thoughts, and alternatives from others.

**Comment by a-type** [comment]
We originally used a ThemeProvider before moving to CSS vars, and I think it's still present actually.

I'm not sure that browser compat is a limiting factor anymore. My understanding is that we may not need to support IE11 at least for new React work. I'm not sure where that leaves us on the support matrix.

**Comment by Aubron** [comment]
What would you say our major reasons for the switch were? What kind of advantages would you say you all got out of it (I'm unfamiliar with using css vars anywhere near production, never had the ability to not have to talk to IE) as opposed to the styled-components solution?

**Comment by zelitzsi** [comment]
The ThemeProvider pattern is still there and is functional; that's how it works in environments that don't support CSS vars.

Honestly I don't think there is a strong case for CSS vars. The main advantages that I see are:
* Easier syntax
* More control over theming full components. For example, we can use CSS vars to give names to the parts of a component and modify those colors easily later. You can give navigation fg, bg, and text css vars at the top level component (which controls whether the component is light, dark, sub nav, etc.) and pass them through into the layers below. If you want to later change the fg color, it's very easy to do so, and it would be trivial to allow library users to modify those settings as well.
* Multiple themes are less confusing. I think you can probably insert multiple ThemeProviders in, but CSS vars just cascade. You can have an admin view inside your normal view with a different theme.
I'm not totally sold on the idea of using CSS vars, but I think they make sense to use if there's no cost to using them (i.e., if we don't have to support IE).

**Comment by Aubron** [comment]
Maybe I'm off the mark here, but I feel like we're not really using them as theming if we're going so far as to provide paths into the individual parts of specific components. For me that kind of use scenario is made possible with the changes to the CSS API I'm proposing here: https://github.com/Bandwidth/shared-components/issues/191

What I'd rather see is something (no one is surprised) more like the material-ui theme, where we don't really specify many per component properties, but instead a general use set of theme variables that components can use where it makes sense: https://material-ui.com/customization/default-theme/

Makes there be a lot less properties to change, and inherently easier to use for end users. If they want to do something specific, to target nested headings of UserInfo components, they can, there's a classname available for that they can just CSS target, `.userInfoHeading` and change them all at once.

**Comment by zelitzsi** [comment]
Our theme object looks fairly similar to the one that you linked. Have you checked out `packages/shared-components/src/themes/irisTheme.js`? It defines a bunch of parameters that a user could modify and retheme with. It doesn't include functions like material-ui, but it is pretty light-weight as a result.

I do think that providing uniform classnames for consumers to target would be useful. We would have to figure out the right approach.

**Comment by Aubron** [comment]
Oh yeah no that seems great, and is what I want to expand upon. I just see the classname approach as more extensible long term than the CSS var route.

**Comment by zelitzsi** [comment]
Sort of. I think they serve slightly different purposes. CSS vars are a tool we have to help style components internally. We could expose those tools so that users can customize components. For example, I might want a component to have a different fg color, but I don't want to look up all of the classnames and override those cases manually. I think we can probably take advantage of both.
