### ISSUE TITLE
Shared Component Guiding Principles

### ISSUE THREAD

**Issue by Aubron** [Bandwidth/shared-components#191]
Most of these are adapted from material-ui, but as probably the world's most used component library, I think they represent a good starting place for our own purposes. I want feedback, tell me why I'm wrong and bad and also wrong.

### React API

1. Undocumented properties supplied to a component are spread to the root element.
2. Any non-native property should be documented in the component. Native props don't need to be documented. (`className`, `onClick`, etc.)
3. Any property that abstracts a native property should use the behavior of that property to guide its implementation, if not use that property internally. (ie: an empty `placeholder` does not magic up a default string, but simply does not render a placeholder)
4. Nested components have their own flattened props when they are key to the top level component abstraction (for example, the `id` prop on an `Input` component). These should be documented.
5. Nested components have a `xxxProps` property when a user might need to tweak the internal render method's sub-components. (for example, if your component has a nested `Input` component, you would provide an `InputProps` object that is spread onto the internal `Input`.
6. If component injection is required (or useful), it is done via a `xxxComponent` property.
7. If a ref of a nested component is exposed, it is done via a `xxxRef` property.
8. The name of a boolean property should be chosen based on the default value. For example, the `disabled` attribute on an input element, if supplied, defaults to true. This allows for shorthand notation:
```
<Input disabled />
```
9. For properties, a boolean is used when 2 degrees of freedom is required (`disabled`, `ripple`, etc). An enum is used when 3 degrees of freedom, or reasonably could be added in the future (`variation`, `animation`, etc)

### CSS API

1. `className` will always style the root element. This ensures the nested component tree is accessible via styled-components.
2. Any sub-component that a user might reasonably wish to style has a className of `${parentComponentName}${SubComponentName}`. For example. If your `UserInfo` component includes a `h1` element as part of its composition, it's className could be 'userInfoHeading'. This allows you to style the `h1` like so, with the raised specificity resulting in limited pollution of the global CSS Namespace:

```
const Info = styled(UserInfo)`
    & .userInfoHeading {
        color: ${props => props.color};
    }
`
```

3. These css properties are documented (Working on how to integrate this into `storybook` easily.)
{[**More to come once we determine our theming solution**](https://github.com/Bandwidth/shared-components/issues/190)}

**Comment by a-type** [comment]
Nothing wrong or bad. These are all great and most of them have been mentioned in passing by the team before.

One thing, for the nested component props object, any reason for PascalCase as opposed to camelCase? I associate PascalCase exclusively with classes in JS.

**Comment by Aubron** [comment]
> One thing, for the nested component props object, any reason for PascalCase as opposed to camelCase? I associate PascalCase exclusively with classes in JS.

My only reasoning for it is that it references a Component.

looking at:
`inputProps`
and
`InputProps`
one feels rather ambiguous, while the other I feel really communicates that this is going talking about the component `Input`, not just referencing the concept of an `input`.

I'm not married to it, but I could see some instances in which the distinction could be useful.

**Comment by a-type** [comment]
I think the `Props` part alone communicates the intent pretty well, personally. I think I've seen other examples of the same pattern in other popular libraries (can't remember which).

**Comment by Aubron** [comment]
So here's my only response to that, and if you're unconvinced I'm willing to drop it off, because I think either way there's minimal confusion.

Imagine a hypothetical `Form` component in our library. It does not implement the `form` tag from html, but instead it is a complex element with custom props.

There are two manners of implementing... some kind of component that could use either a `form` or a `Form` as a nested component. If you implemented it with the `<form>` tag as the nested component, you could use `formProps`, which communicates you're using standard forms, or if you used the advanced `Form` component, `FormProps` lets you know what kind of component is under the hood, without having to read too much into the docs or implementation of the component.

**Comment by a-type** [comment]
Additional proposal: in addition to basic prop spreading, should we also do [ref forwarding](https://reactjs.org/docs/forwarding-refs.html)? I'm a little new to the concept and I'm not sure if it applies here.

**Comment by a-type** [comment]
Alternatively we could use named ref props. I.E. for Accordion, if we felt it necessary, we might have `toggleRef` and `contentRef`. Or, perhaps, we move those to the named prop groups, so you'd have `toggleProps={{ ref }}`, etc.

**Comment by zelitzsi** [comment]
> 1. Undocumented properties supplied to a component are spread to the root element.

Agree 100%.

> 2. Any non-native property should be documented in the component. Native props don't need to be documented. (`className`, `onClick`, etc.)

Agree. Do we want to still include those props in the prop types? I'm not a big prop type stickler personally.

> 3. Any property that abstracts a native property should use the behavior of that property to guide its implementation, if not use that property internally. (ie: an empty `placeholder` does not magic up a default string, but simply does not render a placeholder)

Agree. So basically if a prop is a native property, then it should behave like that property. If it doesn't, it should be called something else.

> 4. Nested components have their own flattened props when they are key to the top level component abstraction (for example, the `id` prop on an `Input` component). These should be documented.

Can you clarify this with an example?

> 5. Nested components have a `xxxProps` property when a user might need to tweak the internal render method's sub-components. (for example, if your component has a nested `Input` component, you would provide an `InputProps` object that is spread onto the internal `Input`.

I want to make sure we continue allowing render props, as I've found them to be pretty useful.

> 6. If component injection is required (or useful), it is done via a `xxxComponent` property.

Agree, but I would want it to be PascalCase, and I don't think it should be a pattern that we heavily promote. In my experience, it is one of the more limiting ways to customize functionality.

> 7. If a ref of a nested component is exposed, it is done via a `xxxRef` property.

How does this work with ref functions? An example would be useful.

> 8. The name of a boolean property should be chosen based on the default value. For example, the `disabled` attribute on an input element, if supplied, defaults to true. This allows for shorthand notation:
```
<Input disabled />
```
Agree. How do we feel about using prop names that follow the format `isEnabled`?

> 9. For properties, a boolean is used when 2 degrees of freedom is required (`disabled`, `ripple`, etc). An enum is used when 3 degrees of freedom, or reasonably could be added in the future (`variation`, `animation`, etc)

Agree. How do we expose and document enum types?

### CSS API

> 1. `className` will always style the root element. This ensures the nested component tree is accessible via styled-components.

Agree. I'm assuming you mean that it doesn't add that classname to components down the tree.

> 2. Any sub-component that a user might reasonably wish to style has a className of `${parentComponentName}${SubComponentName}`. For example. If your `UserInfo` component includes a `h1` element as part of its composition, it's className could be 'userInfoHeading'. This allows you to style the `h1` like so, with the raised specificity resulting in limited pollution of the global CSS Namespace:

```
const Info = styled(UserInfo)`
    & .userInfoHeading {
        color: ${props => props.color};
    }
`
```
Agree, but I think it could get confusing if you have several nested levels or sub components without clearly visible names.

> 3. These css properties are documented (Working on how to integrate this into `storybook` easily.)
{[**More to come once we determine our theming solution**](https://github.com/Bandwidth/shared-components/issues/190)}

Yeah that would probably be a good idea.

**Comment by Aubron** [comment]
@zelitzsi - Nested components example. `Input` renders the following (just providing the shape):

```
<div>
    <input />
</div>
```

We don't rely on `InputProps` to send an id to the input, it is exposed top level as `<Input id="test" />`, because it is key to the top level abstraction. It is documented though, even though its a default, just because it's being elevated.

**Comment by Aubron** [comment]
I agree the ref example would be useful. I'll try and put that in next versions.

Could you clarify what you mean about the `isEnabled` flag? are you talking about the pascal case and/or phrasing of the prop, or the fact that typically isEnabled would be the default.

With the CSS API, visibility is going to be super important there.

**Comment by zelitzsi** [comment]
> are you talking about the pascal case and/or phrasing of the prop
Yes. `isEnabled` vs `enabled`. Personally, I prefer the latter.

**Comment by Aubron** [comment]
Same.

**Comment by a-type** [comment]
Yeah, `is` doesn't add anything... `enabled` is already a boolean state. Same with `valid`, `dirty`, etc.
