### ISSUE TITLE
Basing shared-components on Material-UI

### ISSUE THREAD

**Issue by Aubron** [Bandwidth/shared-components#194]
So I've talked some with @a-type about moving shared-components from a from-scratch initiative to something based on Material UI. I want to provide some pros and cons here, and see what the team feels about it. If we did it, it would function like so:

1. No Material UI Components are 'automatically' exported, we'd only get what we choose to include.
2. If a Material UI Component functions out of the box like we'd like it to, we'd simply export it as our own component.
3. If a component we desire can be made by modifying a material ui component, we override it and export it: https://material-ui.com/customization/overrides/
4. If a component we desire can be made by compositing multiple material ui components, we composite them together and export that.
5. If a component cannot be made by starting from any of the above (unlikely), we make it from scratch, following an api design that mirrors their own.

Instead of porting the shared-components library as it exists today, I would instead probably make it something like `@bandwidth/core` (https://docs.npmjs.com/misc/scope). That way we can slowly transition off shared-components onto the new library while including both, and also because it mirrors material's naming.

### Pros
1. RTL Support
2. Responsive Support
3. Fully tested building blocks makes our components more stable instantly
4. Stable, opinionated, and well-thought-out api and design pattern.
5. Less time doing work that material team has already done.

I could keep listing things that are essentially 'material-ui is a good project, and we would benefit from being made of them', but I won't.

### Cons
1. Transitioning is effort - We haven't really seen too many regressions from our current library. I worry about it, but we don't really have a firm example of why we should do this. Trying to do the initial hump of adapting the components will take effort and time.
2. We lose some ownership of the package and api design.
3. Documentation is hard - I'm working on a documentation method that will read the propTypes and cssApi of the inherited components, as well as the overrides but I don't have a solution for this yet.
4. Material Ui uses JSS instead of styled-components. I don't think this is a huge issue, since material is fully styled-components compatible, including styling nested components. We would likely see some fragmentation and/or migration off of styled-components towards JSS, especially in new projects.
5. Transitioning is effort (again) - Once we have a stable version of `@bandwidth/core`, the ideal scenario would be making an effort to replace the current components in the codebase with it. This wouldn't be a high priority, but it would be a significant effort.

**Comment by zelitzsi** [comment]
It might be useful to see an example of what implementing a component using material-ui would look like. I understand the argument for reusing code that has been vetted and tested extensively by other developers, but I want to make sure that we don't introduce a lot of new problems that are hard to fix (design differences, major differences in how some components are used, etc.)

**Comment by a-type** [comment]
My understanding based on their docs is we could just wrap with `styled()`, right? And they allow us to override nested components the same way?

I like the proposal of `@bandwidth/core`, although I do worry about working too much in a vacuum. I'd want to have a branch of Janus which is integrating the new library ASAP. But the name is shorter, which is a 👍 

Overall I'm a fan of the idea. I'm not even worried about the docs too much. I'd be happy enough to just have any custom properties we add documented, and point everyone to the base MUI components otherwise.

**Comment by Aubron** [comment]
@a-type @zelitzsi - yeah. Example of using a material component with styled-components here:
https://material-ui.com/guides/interoperability/#styled-components

**Comment by Aubron** [comment]
I've opened a branch, `core`, which contains the seeds of this project, including an initial, incomplete pass at a Button component.

**Comment by Aubron** [comment]
One thing I notice immediately is that there's going to need to be a good communication stream between UI/UX and me/us. For example, with the button. The ripple effect. I can disable it, but does UI/UX want it if they get it for free? haha

**Comment by zelitzsi** [comment]
I looked at the `core` branch. I would like to see how much effort it would take to get the button to match up with our current designs visually. My understanding was that we would try using `material-ui` but still present our components in the same visual style. If we are losing out on that or trying to use a standard `material-ui` look & feel, we would need to talk with UX about that.

**Comment by Aubron** [comment]
@zelitzsi - if you're talking about the text, or color, that will not be handled in the button element (with the exception of text spacing). If you're talking about the shadow, animation, and ripple, see my above comment.

**Comment by Aubron** [comment]
If the answer from UX/CX was 'no, we don't want any of that', then I'd probably modify it to be based on ButtonBase, which is a simplified version of the same component.

**Comment by Aubron** [comment]
![screen shot 2018-08-25 at 6 12 28 pm](https://user-images.githubusercontent.com/1171076/44623016-8089b480-a892-11e8-909f-ab2cd4bc9b89.png)

Context of current pass at Button component, so others don't have to start the project to get the context.

Color is being inherited by the theme provider, which will need reimplementation, as is font. (as are shadows technically)

**Comment by zelitzsi** [comment]
I'm talking about the text/color styling. If that is applied at a theme level, I would assume that the button would get the right color. I think in general UX will have an idea of what they want and want to stick fairly close to that.

**Comment by Aubron** [comment]
Yeah that's just because I'm not decorating the component with a revamped ThemeProvider yet. That's my next component to hammer out a solution to. My intent is to do a revamp where I keep some of the 'neat features' like the ripple onClick that Material gives us for free, then sit down with UI/UX and let them tell me what they think doesn't match the visual style they're going for.

**Comment by Aubron** [comment]
I'll also explore where the defaults come from if not wrapped in a themeprovider, and see if I can't modify that as well.

**Comment by zelitzsi** [comment]
It's fine if it's wrapped in `ThemeProvider`; I guess I would also like to see what the revamp for that looks like. I'm sure `material-ui` has their own theming strategy that we need to hook into.

**Comment by Aubron** [comment]
So it does look like we'll need to make sure we use a ThemeProvider. I could override the default theme, but it would remove our ability to ever import a component without modification (it would be wrapped in the non-overridden default theme provider), and add some boilerplate to each component.

**Comment by zelitzsi** [comment]
We should just be able to continue using our existing ThemeProvider right? Or we could include the `material-ui` ThemeProvider as a part of that component? The point is that buttons implemented using `material-ui` should look identical to the ones we have now. If that is easy, then I would be okay with using `material-ui` basic components. If it's hard, then I would be more likely to push back against it.

**Comment by Aubron** [comment]
I'm souring on the idea of `@bandwidth/core`, because I'd like to see things like the node sdk end up in that scope instead of making it nothing but UI stuff.

@zelitzsi - I do think that the themeprovider implementation checks your boxes for simplicity in conversion. We'd have a new themeprovider, that would be based on Material's. Making things look the same as our components has, up to this point, been super simple.
