### ISSUE TITLE
Italic fonts look strange

### ISSUE THREAD

**Issue by a-type** [Bandwidth/shared-components#235]
It's possible that the project isn't properly loading webfonts after we made the transition. I did notice that it's using my local downloaded version, which may not actually have an italic version.

**Comment by zelitzsi** [comment]
Yeah I noticed this as well. I would expect it to always pull from the external font.

**Comment by a-type** [comment]
This was an issue with our project. We weren't loading the fonts correctly since v6 changed the way to do it.

For some reason importing `fonts.css` was broken for us, so I manually pulled in each icon font file. I just forgot to add the Overpass webfont as well.
