### ISSUE TITLE
Upgrade Select & SearchBox to use react-popper

### ISSUE THREAD

**Issue by a-type** [Bandwidth/shared-components#69]
https://github.com/littlebits/react-popover

React-Popover uses portals so it overcomes a lot of the problems with absolute-positioned pop-out sections. A similar approach could help us.

**Comment by a-type** [comment]
https://github.com/JedWatson/react-select/issues/2398

Tracking portal usage in react-select.

**Comment by a-type** [comment]
Update on this: I think a better approach might be to switch to a behavior-driven library like Downshift for apps and provide only visual components from this library.

**Comment by zelitzsi** [comment]
react-popper has been working very well, so we should consider adopting it for Select & SearchBox.
