### ISSUE TITLE
Spacing uses lg size when spacing=null

### ISSUE THREAD

**Issue by zelitzsi** [Bandwidth/shared-components#77]
Consider the following case:
```jsx
<Spacing top="md" size={null}>Content</Spacing>
```

As a result of the how the code works, size will automatically be set to `lg` when it should really set the padding to 0. We may want to have a string that represents zero width - perhaps `none`.

**Comment by zelitzsi** [comment]
Looks like `size="0"` works.

**Comment by a-type** [comment]
Yeah, that was the original usage intention.
